name: GitHub Metrics

on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}] # Roda todos os dias à meia-noite UTC
  # Run workflow manually (opcional: para rodar quando quiser pela aba Actions)
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Permissão necessária para a ação commitar o SVG
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # --- Sua Identidade e Arquivo de Saída ---
          token: ${{ secrets.GITHUB_TOKEN }}
          user: marcosnobre26 # SEU NOME DE USUÁRIO DO GITHUB (NÃO ESQUEÇA DE VERIFICAR!)
          config_timezone: America/Sao_Paulo # SEU FUSO HORÁRIO (ex: America/Sao_Paulo)
          output_filename: github-metrics.svg # Nome do arquivo de saída

          # --- Configurações Visuais para um Look Limpo/Duas Colunas ---
          # O template 'terminal' ou 'repository' pode funcionar melhor para o visual desejado.
          # Vamos começar com 'terminal' por ser mais clean e com bom contraste.
          template: terminal # Experimente 'terminal', 'repository' ou 'classic' com poucos plugins
          theme: github_dark_dimmed # Tema mais suave, menos "pesado" que o dark puro
          # Ou tente: 'github_light', 'gruvbox', 'nord', 'dracula' (se quiser um toque de cor)

          # Base: Apenas o essencial no cabeçalho. Não vamos sobrecarregar aqui.
          base: header, activity # Informações básicas de cabeçalho e atividade.
          
          # Configurações de layout:
          # `compact` para reduzir o espaçamento.
          # `columns` tenta organizar plugins lado a lado, mas é mais efetivo com muitos plugins.
          config_display: compact # Tenta um layout mais denso
          config_padding: 0 # Reduz o padding ao redor dos itens (pode ajudar no visual compacto)
          config_units: yes # Exibe unidades (kB, MB, etc.)

          # --- Plugins Focados e Visuais (Com Moderação) ---

          # 1. Linguagens mais usadas: Essencial e visual.
          plugins_languages: yes
          plugins_languages_sections: most-used # Ou 'recent', 'popular' para ver outras distribuições
          plugins_languages_threshold: 0%      # Inclui todas as linguagens
          plugins_languages_other: no          # Não agrupa em 'Other'
          plugins_languages_indepth: yes       # Análise profunda para maior precisão
          plugins_languages_colors: github     # Cores padrão do GitHub
          plugins_languages_details: bytes, percentage # Mostra bytes e porcentagem
          plugins_languages_limit: 6           # Limite de linguagens para manter o visual limpo

          # 2. Calendário de contribuições: Adiciona um elemento gráfico forte.
          plugins_isocalendar: yes
          plugins_isocalendar_duration: full-year # Ano completo de contribuições

          # 3. Estatísticas de realização (Achievements): Badges que adicionam um toque visual.
          plugins_achievements: yes
          plugins_achievements_threshold: B # Nível de exibição (A, B, C)
          plugins_achievements_secrets: yes # Inclui de repositórios privados
          plugins_achievements_display: detailed # 'compact' ou 'detailed' - vamos tentar detailed para mais presença

          # 4. Atividade Recente: Mostra as últimas ações de forma concisa.
          plugins_activity: yes
          plugins_activity_filter: all # Todos os tipos de atividade
          plugins_activity_limit: 4 # Mostra os 4 eventos mais recentes
          plugins_activity_days: 14 # Atividade dos últimos 14 dias

          # 5. Stargazers: Mostra as estrelas recebidas por seus repositórios.
          plugins_stargazers: yes
          plugins_stargazers_limit: 4 # Limita a 4 repositórios estrelados

          # 6. Wakatime (Se aplicável e configurado): Informação de codificação, impactante visualmente.
          # LEMBRE-SE: Se você usa Wakatime, crie um SECRET 'WAKATIME_TOKEN' no seu repositório.
          # Se NÃO usar Wakatime ou não quiser exibi-lo, REMOVA AS 5 LINHAS ABAIXO.
          plugins_wakatime: yes
          plugins_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          plugins_wakatime_sections: time, languages # Focar em tempo total e linguagens de codificação
          plugins_wakatime_limit: 5 # Limita os itens para cada seção
          plugins_wakatime_days: 7 # Dados dos últimos 7 dias

          # --- Plugins Desativados para Manter a Simplicidade Visual ---
          # Para evitar que a imagem fique muito longa ou poluída, desativamos:
          plugins_topics: no
          plugins_followup: no
          plugins_lines: no
          plugins_traffic: no
          plugins_organizations: no
          plugins_notforked: no